name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: Backend
    steps:
      - name: Pull frontend Docker image
        run: sudo docker pull russole/e-commerce-frontend
      - name: Pull dashboard Docker image
        run: sudo docker pull russole/e-commerce-dashboard
      - name: Pull backend Docker image
        run: sudo docker pull russole/e-commerce-backend
      - name: Delete Old frontend docker container
        run: sudo docker rm -f e-commerce-frontend-container || true
      - name: Delete Old dashboard docker container
        run: sudo docker rm -f e-commerce-dashboard-container || true
      - name: Delete Old backend docker container
        run: sudo docker rm -f e-commerce-backend-container || true
      - name: Run frontend Docker Container
        run: sudo docker run -d -p 3000:3000 --name e-commerce-frontend-container russole/e-commerce-frontend
      - name: Run dashboard Docker Container
        run: sudo docker run -d -p 3001:3001 --name e-commerce-dashboard-container russole/e-commerce-dashboard
      - name: Run backend Docker Container
        run: sudo docker run -d -p 5000:5000 --name e-commerce-backend-container russole/e-commerce-backend #
