name: CI Pipeline

on:
  push:
    branches:
      - "Aws-Deployment"

jobs:
  build:
    runs-on: ubuntu-latest # Workflow Jobs Runs on Github Server(ubuntu-latest) building and pushing the Docker Image

    steps:
      - uses: actions/checkout@v3
        # persist-credentials: false
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the frontend Docker image
        working-directory: frontend
        run: docker build -t russole/e-commerce-frontend .
      - name: Build the Backend Docker image
        working-directory: Backend
        run: docker build -t russole/e-commerce-backend .
      - name: frontend image push to Dockerhub
        run: docker push russole/e-commerce-frontend
      - name: Backend image push to Dockerhub
        run: docker push russole/e-commerce-backend
